version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  test:
    docker:
      - image: circleci/node:12
      - image: mongo:3.6
    steps:
      - checkout
      - puppeteer/install
      - run:
          name: 'Remove pre-installed puppeteer'
          command: |
            rm -rf ./node_modules/
            rm package-lock.json
      - restore_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - run:
          name: 'Install dependencies'
          command: yarn
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: 'Build'
          command: yarn run build
      - run:
          name: 'Check style'
          command: yarn run check
      - run:
          name: 'Run Backend tests'
          working_directory: packages/backend
          command: yarn run test --maxWorkers=2
      - run:
          name: 'Run Frontend tests'
          working_directory: packages/frontend
          command: yarn run test
      - run:
          name: 'Run E2E tests'
          working_directory: packages/test
          command: yarn run test --maxWorkers=2

workflows:
  version: 2
  'build and test':
    jobs:
      - test
